AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM template for BFF (Backend for Frontend) demo.
  Aggregates /posts and /users from JSONPlaceholder.

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Resources:
  BffFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: src/
      Description: BFF Lambda Function that aggregates posts and users
      MemorySize: 128
      Events:
        Api:
          Type: Api
          Properties:
            Path: /posts-with-users
            Method: get
            Auth:
              AuthorizationType: NONE      

Outputs:
  BffApiUrl:
    Description: "API Gateway endpoint URL for BFF function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/posts-with-users"
